### ISSUE TITLE
[BUG] Cypress test doesn't work with ngx-stripe@14.4.1

### ISSUE THREAD

**Issue by PetroSuch** [richnologies/ngx-stripe#201] opened 2023-03-02 13:39 UTC
**Describe the bug**
There is an error when I try to run cypress tests
```
Request URL: https://r.stripe.com/0
Request Method: POST
Status Code: 400 Bad Request
```

Stripe elements don't work in Cypress tests. The iframe is not loaded for example for <ngx-stripe-card-number>

**To Reproduce**
1. Install ngx-stripe@14.4.1
2. Add some stripe elements
3. Run cypress test

**Expected behavior**
To be able to see Stripe elements for Cypress tests and test these elements

**Comment by burnaDLX** [comment] 2023-05-23 10:14
The iframe is not loaded because an outgoing request fails caused by missing headers ([read more here](https://github.com/stripe/stripe-js/issues/234)). 

You can solve this by intercepting the request and add the headers like this:
```
  beforeEach(() => {
      cy.intercept(`https://r.stripe.com/0`, req => {
        req.headers['origin'] = 'https://js.stripe.com';
        req.headers['referer'] = 'https://js.stripe.com/';
      })
  });
```

_Originally posted by @burnaDLX in https://github.com/stripe/stripe-js/issues/234#issuecomment-1558966635_
            

Than the iframe content will show up.

(Tested with v15.6.0)

**Comment by richnologies** [comment] 2023-05-23 16:59
Thanks @burnaDLX. Appreciate the help. Not much experience with Cypress myself. Let's see what's the feedback from @PetroSuch and then we can close it

**Comment by richnologies** [comment] 2023-06-01 22:21
I'm closing this for now. Thanks @burnaDLX for your help. Really appreciate it

**Closed by richnologies** 2023-06-01 22:21 UTC
Labels: triage
