### ISSUE TITLE
[BUG] Can't resolve @angular-devkit/build-angular

### ISSUE THREAD

**Issue by DaSchTour** [richnologies/ngx-stripe#156] opened 2021-11-23 11:22 UTC
**Describe the bug**
When starting (ng serve) my project with angular 13

```
./node_modules/ngx-stripe/fesm2020/ngx-stripe.mjs:1:0-163 - Error: Module not found: Error: Can't resolve '/.../node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator' in '/.../node_modules/ngx-stripe/fesm2020'

```

**Expected behavior**
No dependency to @angular-devkit at runtime

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser node
 - Version 16

**Additional context**

**Comment by richnologies** [comment] 2021-11-23 18:32
Hi @DaSchTour, we don't have any dependency on that library, you can check the `package.json` of the library: 

https://github.com/richnologies/ngx-stripe/blob/main/projects/ngx-stripe/package.json

It is however a devDependency of Angular itself

Can you provide a bit more of context:

- What version of the library
- What version of angular

**Comment by DaSchTour** [comment] 2021-11-23 19:50
Angular and the library are version 13

**Comment by fxck** [comment] 2021-12-07 08:02
same, getting

> ./node_modules/ngx-stripe/fesm2020/ngx-stripe.mjs:1:0-155 - Error: Module not found: Error: Can't resolve '/Users/fxck/www/zerops/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator' in '/Users/fxck/www/zerops/node_modules/ngx-stripe/fesm2020'

**Comment by fxck** [comment] 2021-12-07 08:27
Ok, so the problem seems to disappear with angular 13.0.3 / 4

**Comment by mlc-mlapis** [comment] 2021-12-07 17:36
Let me inform you that the problem is related to the content of the `.angular\cache` directory. If you delete it before compilation, everything works correctly. The compiler recreates it to the up-to-date version.

![image](https://user-images.githubusercontent.com/5693835/145077980-de66af1f-11d5-40ef-8a2c-5c26c1d3a6de.png)

**Comment by richnologies** [comment] 2021-12-09 09:40
Thanks to all of you for your help. I'm closing this issue then, but I will add a section to the docs for this.

**Closed by richnologies** 2021-12-09 09:40 UTC
Labels: triage
