### ISSUE TITLE
wrong definition for Element.on

### ISSUE THREAD

**Issue by rdpeake** [richnologies/ngx-stripe#13] opened 2017-11-24 01:49 UTC
Element on footprint should be 

` on(ev: ElementEventType, handler: (event?: any) => void): void;`

as stripe documentation indicates that a parameter is passed to the handler for some of the events.

**Comment by lujakob** [comment] 2018-01-25 12:20
This is apparently fixed in branch 0.3.0. The problem is this package version is not available in the NPM repository. 'npm view ngx-stripe versions' show the latest version available is 0.2.3
@richnologies Could you please make the latest version available in NPM. Thanks.

**Comment by smlee** [comment] 2018-02-02 00:00
@lujakob 
just bind this and pass in as cb
ex.
```javascript
this.card.on('change', this.onChange.bind(this));

onChange(event) {
  console.log(event)
}
```

**Comment by lujakob** [comment] 2018-02-02 14:22
@smlee Awesome, that works! Thanks.

**Closed** 2018-03-28 10:48 UTC
