### ISSUE TITLE
Similar option .create 

### ISSUE THREAD

**Issue by joepvandepol** [richnologies/ngx-stripe#106] opened 2020-08-19 16:16 UTC
Is there a similar option for 
const charge = await stripe.charges.create({
  amount: 999,
  currency: 'usd',
  description: 'Example charge',
  source: token,
  statement_descriptor: 'Custom descriptor',
});

Or how should I charge a customer for a one time payment? 
I would like to use this similar option also to create a IDEAL payment.

**Comment by richnologies** [comment] 2020-08-19 22:56
Hello @joepvandepol,

Here is a link to the official docs with a complete example for accepting payments with Charges API: https://stripe.com/docs/payments/accept-a-payment-charges

As you can see there are 5 steps, `ngx-stripe` is just a thin wrapper around **Stripe Elements** so we only provide tools to help with Steps 2 and 3, the rest needs to be done in the server and is outside the scope of this module. 

Also, if is up to you, please consider not using charges or tokens, since boot are deprecated APIs and migrate to Payment Intents API, here is more info from the official docs: https://stripe.com/docs/payments/charges-api

I close this now since is not issue with the library, but if you have any more questions please let me know.

R

**Closed by richnologies** 2020-08-19 22:56 UTC
Labels: question

**Comment by joepvandepol** [comment] 2020-08-20 13:36
okay so after a couple of hours I've got something together only I'm stuck 
I've googled my error code and it says that my api keys are some how wrong/messed up 
I've double checked my api keys and there where all fine. Did I forgot something? 
From what I understand does confirmCardPayment created the payment and checks the payment also. I can see the response from my Stripe dashboard. From that, I can conclude that my API keys are right?

    ` this.stripeService.createSource(this.card.element, {
      amount: 100, // in cents
        type: 'card',
        currency: 'eur',
        owner: {
          name: 'name'
        },
      }).subscribe((result)=> {
        console.log("result",result);
        this.stripeService
        .confirmCardPayment(`${result.source?.client_secret}`, {
          payment_method: {
            card: this.card.element,
            billing_details: {
              name: 'name',
            },
          },
        }).subscribe((result => { 
          console.log(result);
        }))
      })`

My error code: 
error:
code: "resource_missing"
doc_url: "https://stripe.com/docs/error-codes/resource-missing"
message: "No such payment_intent: 'src_client'"
param: "intent"
type: "invalid_request_error"
__proto__: Object
__proto__: Object

**Comment by richnologies** [comment] 2020-08-21 01:06
Hello @joepvandepol,

Answering your question in this issue: https://github.com/richnologies/ngx-stripe/issues/107, yes we can keep this conversion even if the issue is closed, so I will also close the other one as duplicate.

**Comment by richnologies** [comment] 2020-08-21 01:17
So, to answer to your question, you're mixing this a bit here. The `createSource` function is related to the old Charges/Tokens APIs and `confirmCardPayment` can only be used with the intents API. The first thing you need to decide is if you're using payment intents or charges. Since I assume this is a new implementation, I'll suggest again using intents.

When we are using Payment Intents API the first step is to call our backend to ask for a Payment Intent. This needs to be an HTTP call to your server, the StripeService won't handle that for you. Once the server answer with a Payment Intent object, then you can pass the client_secret to the `confirmCardPayment` as you are doing right now. So in summary, the first call I'd say is wrong, the second one is right. 

Take a look at this example in the docs: https://richnologies.gitbook.io/ngx-stripe/examples#collect-payment-intent

Notice how in line 60, within the pay function we call the `createPaymentIntent` method, but this is not part of ngx-stripe, is just a POST request to the backend. You even have a file `server.js` in this example with a very minimalistic example of how to create a payment intent in Node.js. Then with the result we call the `confirmCardPayment` same way you do. 

Hope this example helps you. 

R

**Comment by tahir-jamil** [comment] 2021-06-28 23:36
hi @richnologies your above explanation is really good
i have payment intent object and also the client secret key but then i call confirmCardPayment then i got this error message below
```
code: "resource_missing"
doc_url: "https://stripe.com/docs/error-codes/resource-missing"
message: "No such payment_intent: 'pi_1J7TyTPVOJ8GVo8n4RlKoKKT'"
param: "intent"
type: "invalid_request_error"
__proto__: Object
```
my secret key and my publisher key both are correct in frontend and backend 
hear is the implementation 
```
this.createPaymentIntent(this.stripeTest.get('amount').value, loggedInUserId)
          .pipe(
            switchMap((pi: any): Observable<any> => // if) {
                (pi && pi).paymentIntent && this.stripeService.confirmCardPayment(pi.paymentIntent.client_secret, {
                  payment_method: {
                    card: this.card.element,
                    billing_details: {
                      name: this.stripeTest.get('name').value,
                    }
                  },
                })
            )
          )
          .subscribe((result) => {
            if (result.error) {
              // Show error to your customer (e.g., insufficient funds)
              console.log(result.error.message);
            } else {
              // The payment has been processed!
              if (result.paymentIntent.status === 'succeeded') {
                this.dialogRef.close(result)
                // Show a success message to your customer
              }
            }
          }, (error) => {
            this.payable = false;
          });
```

i'm stuck please guide me

**Comment by richnologies** [comment] 2021-06-29 20:12
Hi @tahir-jamil, happy to help. 

Something similar happened to me like a year ago. Let me ask you a question. Are you using Stripe Connect?

In my case the reason was that the intent was created in the connected account, but I was try to confirmed it in the main account. I can provide you a working flow if that is the case. 

Let me know if helps you

R
